### PR TITLE
podman is required.  also, "files" subdirectory here is incorrect.

### PR DESCRIPTION
**Pull request by arichnad**
podman is required.  "docker build -v" does not exist, this is only in podman.

"files" subdirectory here is incorrect.

### CODE REVIEW

**Comment by akien-mga** [comment]
> "files" subdirectory here is incorrect.

Why? It's this folder: https://github.com/godotengine/build-containers/tree/master/files
That's where the SDK archives should be put.

I've used it several times to build the Xcode image, it works fine.

**Comment by arichnad** [comment]
> I've used it several times to build the Xcode image, it works fine.

@akien-mga I believe you have.  But please explain how this could possibly work:

`files_root=$(pwd)/files`
then
`${files_root}/files`

won't this be `$(pwd)/files/files` ?

I don't have a files/files, and I'm guessing you don't either?

**Comment by akien-mga** [comment]
Ah I see, the change is correct indeed. This was a regression from 86739a8185a5, and apparently I didn't rebuild the Xcode container since then.

**Comment by akien-mga** [comment]
Thanks!

**Comment by arichnad** [comment]
Hey @akien-mga, sorry, I'm not sure who to contact about this:  How do I make this file: `aarch64-apple-darwin-mono-sgen.tar.xz`  It's fine if I need to use a mac, or something, just whatever notes you have on how to make this file, please let me know, thanks!

**Pull request merged**
